In [4]:


import joblib

X_train = joblib.load(
    "X_train_strat.pkl"
)

X_test = joblib.load(
    "X_test_strat.pkl"
)

y_train = joblib.load(
    "y_train_strat.pkl"
)

y_test = joblib.load(
    "y_test_strat.pkl"
)

In [6]:
print(type(X_train))
print(X_train.shape)
print(X_train.index[:10])

<class 'mordred._base.pandas_module.MordredDataFrame'>
(7984, 2453)
Index([1506, 8105, 5152, 3295, 4337, 9097, 9229, 2778, 4731, 9165], dtype='int64')

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\jeshw\Downloads\aqsoldb.csv")

print(df.index[:10])
print(df[['Drug_ID']].head())

RangeIndex(start=0, stop=10, step=1)
                                             Drug_ID
0         N,N,N-trimethyloctadecan-1-aminium bromide
1                           Benzo[cd]indol-2(1H)-one
2                               4-chlorobenzaldehyde
3  zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...
4  4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...

In [16]:
df.head()

,Drug_ID,Drug,Y
0,"N,N,N-trimethyloctadecan-1-aminium bromide",CCCCCCCCCCCCCCCCCC[N+](C)(C)C.[Br-],-3.616127
1,Benzo[cd]indol-2(1H)-one,O=C1Nc2cccc3cccc1c23,-3.254767
2,4-chlorobenzaldehyde,O=Cc1ccc(Cl)cc1,-2.177078
3,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",CC(c1ccccc1)c1cc(C(=O)[O-])c(O)c(C(C)c2ccccc2)...,-3.924409
4,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,c1cc(N(CC2CO2)CC2CO2)ccc1Cc1ccc(N(CC2CO2)CC2CO...,-4.662065

In [15]:

print(df.index[:10])

RangeIndex(start=0, stop=10, step=1)

In [10]:
X_train.index[:10]

Index([1506, 8105, 5152, 3295, 4337, 9097, 9229, 2778, 4731, 9165], dtype='int64')

In [11]:
df.loc[1506, "Drug_ID"]

'diisotridecyl adipate'

In [12]:
df.loc[8105, "Drug_ID"]

'purin-6-ylmercaptomethyl butyrate; s-butanoyloxymethyl-6-mercaptopurine; butanoic acid 9h-purin-6-ylthiomethyl ester'

In [13]:
print(df.loc[1506, "Drug_ID"])
print(df.loc[8105, "Drug_ID"])

diisotridecyl adipate
purin-6-ylmercaptomethyl butyrate; s-butanoyloxymethyl-6-mercaptopurine; butanoic acid 9h-purin-6-ylthiomethyl ester

In [14]:
print(X_test.index[:10])

Index([8107, 3757, 3485, 5796, 6731, 1147, 9398, 6329, 7694, 5206], dtype='int64')

In [17]:
print(len(X_train.index))

7984

In [18]:
print(max(X_train.index))

9979

In [19]:
idx = 8105

drug_id = df.loc[idx, "Drug_ID"]

features = X_train.loc[[idx]]

features.insert(0, "Drug_ID", drug_id)

display(features)

,Drug_ID,DESC_ABC,DESC_ABCGG,DESC_nAcid,DESC_nBase,DESC_SpAbs_A,DESC_SpMax_A,DESC_SpDiam_A,DESC_SpAD_A,DESC_SpMAD_A,...,FPMorgan_1014,FPMorgan_1015,FPMorgan_1016,FPMorgan_1017,FPMorgan_1018,FPMorgan_1019,FPMorgan_1020,FPMorgan_1021,FPMorgan_1022,FPMorgan_1023
8105,purin-6-ylmercaptomethyl butyrate; s-butanoylo...,12.975211,11.10919,1,0,21.230308,2.335667,4.671335,21.230308,1.248842,...,0,0,0,0,0,0,0,0,0,0

In [28]:
import joblib

selected_features = joblib.load(
    "selected_1000_features.pkl"
)

print(type(selected_features))
print(len(selected_features))

<class 'pandas.core.indexes.base.Index'>
1000

In [29]:
print(X_train.shape)

print(len(selected_features))

(7984, 2453)
1000

In [30]:
%whos

Variable            Type                Data/Info
-------------------------------------------------
X_test              MordredDataFrame           DESC_ABC  DESC_ABC<...>1996 rows x 2453 columns]
X_train             MordredDataFrame           DESC_ABC  DESC_ABC<...>7984 rows x 2453 columns]
df                  DataFrame                                    <...>\n[9982 rows x 3 columns]
drug_id             str                 purin-6-ylmercaptomethyl <...>urin-6-ylthiomethyl ester
f                   BufferedReader      <_io.BufferedReader name='descriptor_df'>
features            MordredDataFrame                             <...>\n[1 rows x 2454 columns]
idx                 int                 8105
joblib              module              <module 'joblib' from 'c:<...>es\\joblib\\__init__.py'>
os                  module              <module 'os' from 'c:\\Us<...>ubility_env\\lib\\os.py'>
pd                  module              <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
selected_features   Index               Index(['DESC_ABC', 'DESC_<...>pe='object', length=1000)
y_test              Series              8107   -7.510000\n3757   <...>gth: 1996, dtype: float64
y_train             Series              1506   -5.708288\n8105   <...>gth: 7984, dtype: float64

In [31]:
X_full = pd.concat(
    [X_train, X_test],
    axis=0
)

print(X_full.shape)

(9980, 2453)

In [32]:
full_2453 = X_full.copy()

full_2453.insert(
    0,
    "Drug_ID",
    df.loc[full_2453.index, "Drug_ID"]
)

full_2453.insert(
    0,
    "Index",
    full_2453.index
)

print(full_2453.shape)

(9980, 2455)

In [33]:
full_2453.to_csv(
    "all_2453_features_with_drugid.csv",
    index=False
)

In [34]:
import pandas as pd

In [35]:
full_df = pd.read_csv("all_2453_features_with_drugid.csv")

In [37]:
full_df.head()

,Index,Drug_ID,DESC_ABC,DESC_ABCGG,DESC_nAcid,DESC_nBase,DESC_SpAbs_A,DESC_SpMax_A,DESC_SpDiam_A,DESC_SpAD_A,...,FPMorgan_1014,FPMorgan_1015,FPMorgan_1016,FPMorgan_1017,FPMorgan_1018,FPMorgan_1019,FPMorgan_1020,FPMorgan_1021,FPMorgan_1022,FPMorgan_1023
0,1506,diisotridecyl adipate,25.405076,17.345586,0,0,43.447485,2.085617,4.171234,43.447485,...,0,0,0,0,0,0,0,0,0,0
1,8105,purin-6-ylmercaptomethyl butyrate; s-butanoylo...,12.975211,11.109190,1,0,21.230308,2.335667,4.671335,21.230308,...,0,0,0,0,0,0,0,0,0,0
2,5152,"2,3-dichloronitrobenzene",14.459973,13.994774,0,0,25.055466,2.364871,4.729742,25.055466,...,0,0,0,0,0,0,0,0,0,0
3,3295,"disodium (6Z)-4-amino-3-[4-[[4-(2,4-diaminophe...",43.439687,28.997336,2,0,69.282695,2.556324,5.112647,69.282695,...,0,0,0,0,0,0,0,0,0,0
4,4337,"2-butenoic acid, 4-[(aminocarbonyl)amino]-4-oxo-",7.618017,7.649777,1,0,11.812926,2.092177,4.184353,11.812926,...,0,0,0,0,0,0,0,0,0,0

In [38]:
selected_1000 = X_full[
    selected_features
].copy()

In [39]:
print(selected_1000.shape)

(9980, 1000)

In [40]:
selected_1000.insert(
    0,
    "Drug_ID",
    df.loc[selected_1000.index, "Drug_ID"]
)

selected_1000.insert(
    0,
    "Index",
    selected_1000.index
)

In [41]:
print(selected_1000.shape)

(9980, 1002)

In [42]:
selected_1000.to_csv(
    "selected_1000_features_with_drugid.csv",
    index=False
)

In [43]:
selected_1000.head()

,Index,Drug_ID,DESC_ABC,DESC_ABCGG,DESC_nAcid,DESC_nBase,DESC_SpAbs_A,DESC_SpMax_A,DESC_SpDiam_A,DESC_SpAD_A,...,FPMorgan_941,FPMorgan_946,FPMorgan_947,FPMorgan_960,FPMorgan_967,FPMorgan_974,FPMorgan_981,FPMorgan_984,FPMorgan_997,FPMorgan_1011
1506,1506,diisotridecyl adipate,25.405076,17.345586,0,0,43.447485,2.085617,4.171234,43.447485,...,0,0,0,0,0,0,0,0,0,0
8105,8105,purin-6-ylmercaptomethyl butyrate; s-butanoylo...,12.975211,11.109190,1,0,21.230308,2.335667,4.671335,21.230308,...,0,0,0,0,1,0,0,0,0,0
5152,5152,"2,3-dichloronitrobenzene",14.459973,13.994774,0,0,25.055466,2.364871,4.729742,25.055466,...,0,0,0,0,0,0,0,0,0,0
3295,3295,"disodium (6Z)-4-amino-3-[4-[[4-(2,4-diaminophe...",43.439687,28.997336,2,0,69.282695,2.556324,5.112647,69.282695,...,0,0,0,0,0,0,0,0,0,0
4337,4337,"2-butenoic acid, 4-[(aminocarbonyl)amino]-4-oxo-",7.618017,7.649777,1,0,11.812926,2.092177,4.184353,11.812926,...,0,0,0,0,0,0,0,0,0,0

In [44]:
pd.DataFrame(
    selected_features,
    columns=["Feature_Name"]
).to_csv(
    "selected_1000_feature_names.csv",
    index=False
)