In [1]:
import pandas as pd
import numpy as np

from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.Chem import SaltRemover
from rdkit.Chem.MolStandardize import rdMolStandardize

In [2]:
df = pd.read_csv(r"C:\Users\jeshw\Downloads\aqsoldb.csv")

In [3]:
df.head()

,Drug_ID,Drug,Y
0,"N,N,N-trimethyloctadecan-1-aminium bromide",CCCCCCCCCCCCCCCCCC[N+](C)(C)C.[Br-],-3.616127
1,Benzo[cd]indol-2(1H)-one,O=C1Nc2cccc3cccc1c23,-3.254767
2,4-chlorobenzaldehyde,O=Cc1ccc(Cl)cc1,-2.177078
3,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",CC(c1ccccc1)c1cc(C(=O)[O-])c(O)c(C(C)c2ccccc2)...,-3.924409
4,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,c1cc(N(CC2CO2)CC2CO2)ccc1Cc1ccc(N(CC2CO2)CC2CO...,-4.662065

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9982 entries, 0 to 9981
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Drug_ID  9982 non-null   object
 1   Drug     9982 non-null   object
 2   Y        9982 non-null   float64
dtypes: float64(1), object(2)
memory usage: 234.1+ KB

In [5]:
from rdkit import RDLogger

RDLogger.DisableLog('rdApp.*')

In [6]:
from rdkit import Chem
from rdkit.Chem.SaltRemover import SaltRemover

In [7]:
from rdkit import Chem
from rdkit.Chem import SaltRemover
from rdkit.Chem.MolStandardize import rdMolStandardize

remover = SaltRemover.SaltRemover()

largest_fragment_chooser = (
    rdMolStandardize.LargestFragmentChooser()
)

def clean_molecule(smiles):

    try:

        mol = Chem.MolFromSmiles(smiles)

        if mol is None:
            return None

        mol = remover.StripMol(mol)

        mol = largest_fragment_chooser.choose(
            mol
        )

        Chem.SanitizeMol(mol)

        return mol

    except:
        return None

print("Before Cleaning:")
print(df.shape)

df["mol"] = df["Drug"].apply(
    clean_molecule
)

df = df[
    df["mol"].notnull()
].reset_index(drop=True)

print("\nAfter Cleaning:")
print(df.shape)

Before Cleaning:
(9982, 3)

After Cleaning:
(9980, 4)

In [8]:
df.head()

,Drug_ID,Drug,Y,mol
0,"N,N,N-trimethyloctadecan-1-aminium bromide",CCCCCCCCCCCCCCCCCC[N+](C)(C)C.[Br-],-3.616127,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...
1,Benzo[cd]indol-2(1H)-one,O=C1Nc2cccc3cccc1c23,-3.254767,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...
2,4-chlorobenzaldehyde,O=Cc1ccc(Cl)cc1,-2.177078,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...
3,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",CC(c1ccccc1)c1cc(C(=O)[O-])c(O)c(C(C)c2ccccc2)...,-3.924409,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...
4,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,c1cc(N(CC2CO2)CC2CO2)ccc1Cc1ccc(N(CC2CO2)CC2CO...,-4.662065,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...

In [9]:
df["clean_smiles"] = df["mol"].apply(
    Chem.MolToSmiles
)

df.head()

,Drug_ID,Drug,Y,mol,clean_smiles
0,"N,N,N-trimethyloctadecan-1-aminium bromide",CCCCCCCCCCCCCCCCCC[N+](C)(C)C.[Br-],-3.616127,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...,CCCCCCCCCCCCCCCCCC[N+](C)(C)C
1,Benzo[cd]indol-2(1H)-one,O=C1Nc2cccc3cccc1c23,-3.254767,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...,O=C1Nc2cccc3cccc1c23
2,4-chlorobenzaldehyde,O=Cc1ccc(Cl)cc1,-2.177078,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...,O=Cc1ccc(Cl)cc1
3,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",CC(c1ccccc1)c1cc(C(=O)[O-])c(O)c(C(C)c2ccccc2)...,-3.924409,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...,CC(c1ccccc1)c1cc(C(=O)[O-])c(O)c(C(C)c2ccccc2)c1
4,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,c1cc(N(CC2CO2)CC2CO2)ccc1Cc1ccc(N(CC2CO2)CC2CO...,-4.662065,<rdkit.Chem.rdchem.Mol object at 0x00000259B81...,c1cc(N(CC2CO2)CC2CO2)ccc1Cc1ccc(N(CC2CO2)CC2CO...

In [10]:
import numpy as np

np.float = float
np.int = int
np.bool = bool
np.object = object

from mordred import Calculator, descriptors

calc = Calculator(
    descriptors,
    ignore_3D=True
)

descriptor_df = calc.pandas(
    df["mol"]
)

print("Descriptor Shape:")
print(descriptor_df.shape)

  1%|          | 55/9980 [00:03<05:00, 32.98it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

  1%|          | 78/9980 [00:04<05:23, 30.65it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  1%|          | 112/9980 [00:06<06:08, 26.80it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  2%|▏         | 157/9980 [00:06<03:03, 53.61it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

  3%|▎         | 283/9980 [00:09<02:44, 59.01it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

  4%|▎         | 359/9980 [00:10<02:44, 58.37it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

  4%|▍         | 431/9980 [00:11<01:50, 86.29it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

  5%|▌         | 503/9980 [00:13<03:17, 48.10it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  9%|▉         | 920/9980 [00:20<02:36, 57.74it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 10%|▉         | 972/9980 [00:21<02:35, 57.93it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 10%|▉         | 974/9980 [00:22<03:10, 47.16it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 11%|█         | 1091/9980 [00:23<02:14, 66.09it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 12%|█▏        | 1234/9980 [00:28<04:46, 30.49it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 13%|█▎        | 1284/9980 [00:28<02:30, 57.97it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 13%|█▎        | 1313/9980 [00:29<02:34, 56.23it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 14%|█▍        | 1375/9980 [00:31<04:57, 28.92it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 14%|█▍        | 1423/9980 [00:32<03:16, 43.52it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 15%|█▍        | 1467/9980 [00:38<16:46,  8.46it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 16%|█▌        | 1551/9980 [00:40<05:26, 25.80it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 16%|█▌        | 1604/9980 [00:42<04:19, 32.22it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 17%|█▋        | 1724/9980 [00:48<06:20, 21.72it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 18%|█▊        | 1799/9980 [00:51<05:42, 23.88it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 19%|█▊        | 1852/9980 [00:52<03:50, 35.25it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 19%|█▉        | 1924/9980 [00:54<02:39, 50.50it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 20%|██        | 2006/9980 [00:57<04:58, 26.75it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 21%|██        | 2091/9980 [00:59<03:33, 37.01it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 22%|██▏       | 2219/9980 [01:02<02:58, 43.56it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 23%|██▎       | 2274/9980 [01:04<05:40, 22.63it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 26%|██▌       | 2557/9980 [01:14<03:35, 34.50it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

 27%|██▋       | 2721/9980 [01:21<02:13, 54.42it/s]

c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Autocorrelation.py:97: RuntimeWarning: Mean of empty slice.
  return avec - avec.mean()
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
c:\Users\jeshw\anaconda3\envs\solubility_env\lib\site-packages\mordred\Constitutional.py:80: RuntimeWarning: invalid value encountered in double_scalars
  return S / self.mol.GetNumAtoms()

100%|██████████| 9980/9980 [04:21<00:00, 38.19it/s]

Descriptor Shape:
(9980, 1613)

In [11]:
descriptor_df.head()

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,15.325998,11.908140,0,1,26.071695,2.12132,4.24264,26.071695,1.185077,3.91795,...,8.878079,53.228660,312.362477,4.593566,1716,19,88.0,86.0,8.3125,5.375000
1,10.554231,8.981734,0,0,17.518893,2.503145,4.873772,17.518893,1.347607,3.552497,...,9.744550,59.616539,169.052764,8.452638,207,21,74.0,91.0,3.305556,2.777778
2,6.473351,6.127583,0,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,8.590258,37.289972,140.002892,10.000207,90,9,40.0,43.0,3.472222,2.166667
3,20.062858,16.645175,1,0,33.660518,2.453396,4.906793,33.660518,1.294635,4.179367,...,10.169576,60.967815,345.149618,7.343609,1602,43,134.0,158.0,9.0,5.777778
4,25.374964,18.024219,0,0,42.485221,2.398507,4.736543,42.485221,1.370491,4.465186,...,10.351150,90.719091,422.220557,6.921648,3248,42,174.0,206.0,6.361111,6.555556

In [12]:
descriptor_df = descriptor_df.apply(
    pd.to_numeric,
    errors="coerce"
)

print(descriptor_df.shape)

descriptor_df.head()

(9980, 1613)

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,15.325998,11.908140,0,1,26.071695,2.121320,4.242640,26.071695,1.185077,3.917950,...,8.878079,53.228660,312.362477,4.593566,1716,19,88.0,86.0,8.312500,5.375000
1,10.554231,8.981734,0,0,17.518893,2.503145,4.873772,17.518893,1.347607,3.552497,...,9.744550,59.616539,169.052764,8.452638,207,21,74.0,91.0,3.305556,2.777778
2,6.473351,6.127583,0,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,8.590258,37.289972,140.002892,10.000207,90,9,40.0,43.0,3.472222,2.166667
3,20.062858,16.645175,1,0,33.660518,2.453396,4.906793,33.660518,1.294635,4.179367,...,10.169576,60.967815,345.149618,7.343609,1602,43,134.0,158.0,9.000000,5.777778
4,25.374964,18.024219,0,0,42.485221,2.398507,4.736543,42.485221,1.370491,4.465186,...,10.351150,90.719091,422.220557,6.921648,3248,42,174.0,206.0,6.361111,6.555556

In [13]:
missing_percent = (

    descriptor_df
    .isnull()
    .mean()
    * 100

)

missing_df = pd.DataFrame({

    "Missing_Percentage": missing_percent

}).sort_values(

    by="Missing_Percentage",
    ascending=False
)

print(missing_df.head(20))

           Missing_Percentage
MINssPbH2               100.0
MAXsGeH3                100.0
MAXsssGeH               100.0
MAXssssGe               100.0
MAXsAsH2                100.0
MAXssAsH                100.0
MAXssBH                 100.0
MAXssssBe               100.0
MAXssBe                 100.0
MAXsLi                  100.0
MINddssSe               100.0
MAXsSeH                 100.0
MAXdSe                  100.0
MAXddssSe               100.0
MAXsSnH3                100.0
MAXssSnH2               100.0
MAXsssSnH               100.0
MAXsPbH3                100.0
MAXssPbH2               100.0
MAXssGeH2               100.0

In [14]:
missing_threshold = 40

columns_to_keep = missing_percent[
    missing_percent <= missing_threshold
].index

descriptor_df = descriptor_df[
    columns_to_keep
]

print("Descriptor Shape After Missing Value Filtering:")
print(descriptor_df.shape)

Descriptor Shape After Missing Value Filtering:
(9980, 1429)

In [15]:
from rdkit.Chem import AllChem

def generate_fingerprint(mol):

    return list(

        AllChem.GetMorganFingerprintAsBitVect(
            mol,
            radius=2,
            nBits=1024
        )

    )

fingerprints = df["mol"].apply(
    generate_fingerprint
)

fingerprint_df = pd.DataFrame(
    fingerprints.tolist()
)

print("Fingerprint Shape:")
print(fingerprint_df.shape)

Fingerprint Shape:
(9980, 1024)

In [16]:
fingerprint_df.columns = [

    f"FPMorgan_{i}"

    for i in range(
        fingerprint_df.shape[1]
    )
]

In [17]:
fingerprint_df.head()

,FPMorgan_0,FPMorgan_1,FPMorgan_2,FPMorgan_3,FPMorgan_4,FPMorgan_5,FPMorgan_6,FPMorgan_7,FPMorgan_8,FPMorgan_9,...,FPMorgan_1014,FPMorgan_1015,FPMorgan_1016,FPMorgan_1017,FPMorgan_1018,FPMorgan_1019,FPMorgan_1020,FPMorgan_1021,FPMorgan_1022,FPMorgan_1023
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [18]:
descriptor_df.columns = [

    f"DESC_{col}"

    for col in descriptor_df.columns
]

In [19]:
descriptor_df.head()

,DESC_ABC,DESC_ABCGG,DESC_nAcid,DESC_nBase,DESC_SpAbs_A,DESC_SpMax_A,DESC_SpDiam_A,DESC_SpAD_A,DESC_SpMAD_A,DESC_LogEE_A,...,DESC_SRW10,DESC_TSRW10,DESC_MW,DESC_AMW,DESC_WPath,DESC_WPol,DESC_Zagreb1,DESC_Zagreb2,DESC_mZagreb1,DESC_mZagreb2
0,15.325998,11.908140,0,1,26.071695,2.121320,4.242640,26.071695,1.185077,3.917950,...,8.878079,53.228660,312.362477,4.593566,1716,19,88.0,86.0,8.312500,5.375000
1,10.554231,8.981734,0,0,17.518893,2.503145,4.873772,17.518893,1.347607,3.552497,...,9.744550,59.616539,169.052764,8.452638,207,21,74.0,91.0,3.305556,2.777778
2,6.473351,6.127583,0,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,8.590258,37.289972,140.002892,10.000207,90,9,40.0,43.0,3.472222,2.166667
3,20.062858,16.645175,1,0,33.660518,2.453396,4.906793,33.660518,1.294635,4.179367,...,10.169576,60.967815,345.149618,7.343609,1602,43,134.0,158.0,9.000000,5.777778
4,25.374964,18.024219,0,0,42.485221,2.398507,4.736543,42.485221,1.370491,4.465186,...,10.351150,90.719091,422.220557,6.921648,3248,42,174.0,206.0,6.361111,6.555556

In [20]:
X = pd.concat(

    [descriptor_df, fingerprint_df],

    axis=1
)

In [21]:
sol_desc=X.to_csv("descriptor_df", index=False)

In [22]:
X.head()

,DESC_ABC,DESC_ABCGG,DESC_nAcid,DESC_nBase,DESC_SpAbs_A,DESC_SpMax_A,DESC_SpDiam_A,DESC_SpAD_A,DESC_SpMAD_A,DESC_LogEE_A,...,FPMorgan_1014,FPMorgan_1015,FPMorgan_1016,FPMorgan_1017,FPMorgan_1018,FPMorgan_1019,FPMorgan_1020,FPMorgan_1021,FPMorgan_1022,FPMorgan_1023
0,15.325998,11.908140,0,1,26.071695,2.121320,4.242640,26.071695,1.185077,3.917950,...,0,0,0,0,0,0,0,0,0,0
1,10.554231,8.981734,0,0,17.518893,2.503145,4.873772,17.518893,1.347607,3.552497,...,0,0,0,0,0,0,0,0,0,0
2,6.473351,6.127583,0,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,0,0,0,0,0,0,0,0,0,0
3,20.062858,16.645175,1,0,33.660518,2.453396,4.906793,33.660518,1.294635,4.179367,...,0,0,0,0,0,0,0,0,0,0
4,25.374964,18.024219,0,0,42.485221,2.398507,4.736543,42.485221,1.370491,4.465186,...,0,0,0,0,0,1,0,0,0,0

In [23]:
y = df["Y"]

In [24]:
sol_target = y.to_csv("Y",index=False)

In [25]:
import os 
print(os.getcwd())

c:\Users\jeshw\Desktop\99_sol\notebooks

In [26]:
print("Combined Feature Shape:")
print(X.shape)

print("Target Shape:")
print(y.shape)

Combined Feature Shape:
(9980, 2453)
Target Shape:
(9980,)

In [27]:
import joblib

In [28]:
joblib.dump(
    X.columns.tolist(),
    "final_feature_columns.pkl"
)

print("Final feature columns saved.")

Final feature columns saved.

In [ ]:
from sklearn.model_selection import train_test_split

X_train_random, X_test_random, y_train_random, y_test_random = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42
)

print("X_train_random:", X_train_random.shape)
print("X_test_random :", X_test_random.shape)

print("y_train_random:", y_train_random.shape)
print("y_test_random :", y_test_random.shape)

In [29]:
import joblib

joblib.dump(
    X_train_random,
    "X_train_random.pkl"
)

joblib.dump(
    X_test_random,
    "X_test_random.pkl"
)

joblib.dump(
    y_train_random,
    "y_train_random.pkl"
)

joblib.dump(
    y_test_random,
    "y_test_random.pkl"
)

print("Cleaned random split artifacts saved.")

NameError: name 'X_train_random' is not defined

In [30]:
num_bins = 5

y_bins = pd.qcut(

    y,

    q=num_bins,

    labels=False,

    duplicates="drop"
)

print(
    y_bins.value_counts()
)

Y
2    1999
1    1996
3    1996
0    1996
4    1993
Name: count, dtype: int64

In [31]:
from sklearn.model_selection import train_test_split

X_train_strat, X_test_strat, y_train_strat, y_test_strat = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y_bins
)

print("X_train_strat:", X_train_strat.shape)
print("X_test_strat :", X_test_strat.shape)

print("y_train_strat:", y_train_strat.shape)
print("y_test_strat :", y_test_strat.shape)

X_train_strat: (7984, 2453)
X_test_strat : (1996, 2453)
y_train_strat: (7984,)
y_test_strat : (1996,)

In [32]:
joblib.dump(
    X_train_strat,
    "X_train_strat.pkl"
)

joblib.dump(
    X_test_strat,
    "X_test_strat.pkl"
)

joblib.dump(
    y_train_strat,
    "y_train_strat.pkl"
)

joblib.dump(
    y_test_strat,
    "y_test_strat.pkl"
)

print("Cleaned stratified split artifacts saved.")

Cleaned stratified split artifacts saved.

In [33]:
import joblib

X_train = joblib.load(
    "X_train_random.pkl"
)

X_test = joblib.load(
    "X_test_random.pkl"
)

y_train = joblib.load(
    "y_train_random.pkl"
)

y_test = joblib.load(
    "y_test_random.pkl"
)

In [34]:
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import (
    VarianceThreshold,
    SelectKBest,
    f_regression
)

In [35]:
preprocessor = Pipeline([

    (
        "imputer",
        SimpleImputer(strategy="median")
    ),

    (
        "variance_filter",
        VarianceThreshold(threshold=0.0)
    ),

    (
        "scaler",
        StandardScaler()
    ),

    (
        "feature_selection",
        SelectKBest(
            score_func=f_regression,
            k=1000
        )
    )

])

In [ ]:
from lightgbm import LGBMRegressor

from xgboost import XGBRegressor

from catboost import CatBoostRegressor

from sklearn.ensemble import RandomForestRegressor

from sklearn.svm import SVR

In [ ]:
from sklearn.neural_network import MLPRegressor

In [ ]:

# MODEL PIPELINES


lgbm_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        LGBMRegressor(
            n_estimators=300,
            random_state=42
        )
    )

])


xgb_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        XGBRegressor(
            n_estimators=300,
            random_state=42
        )
    )

])


cat_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        CatBoostRegressor(
            iterations=300,
            verbose=0,
            random_state=42,
            allow_writing_files=False
        )
    )

])


rf_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        RandomForestRegressor(
            n_estimators=300,
            random_state=42,
            n_jobs=-1, 
            max_depth=6
        )
    )

])

svr_pipeline = Pipeline([

    ("preprocessing", preprocessor),

    (
        "model",
        SVR(
            kernel="rbf",
            C=10,
            epsilon=0.1
        )
    )

])

mlp_pipeline = Pipeline([
    
    ('preprocessor', preprocessor),
    (
        'model',MLPRegressor (
    
    
                hidden_layer_sizes = (256,128),
                activation = 'relu',
                solver = 'adam',
                alpha = 0.0001,
                batch_size = 'auto',
                learning_rate = 'adaptive',
                learning_rate_init = 0.0001,
                max_iter = 500,
                early_stopping= True,
                random_state = 42
        )
        
    )
    
])



# STORE ALL MODELS


models = {

    "LightGBM": lgbm_pipeline,

    "XGBoost": xgb_pipeline,

    "CatBoost": cat_pipeline,

    "RandomForest": rf_pipeline,
    
    "SVR": svr_pipeline,
    
    "MLpRegressor": mlp_pipeline

}

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.model_selection import cross_val_score

results = []

for model_name, pipeline in models.items():

    cv_scores = cross_val_score(

        pipeline,

        X_train,

        y_train,

        cv=5,

        scoring="r2",

        n_jobs=-1

    )

    results.append({

        "Model": model_name,

        "CV Mean R2": cv_scores.mean(),

        "CV Std": cv_scores.std()

    })

   
    print(model_name)
   

    print("CV Scores:")
    print(cv_scores)

    print("\nMean CV R2:")
    print(cv_scores.mean())

In [ ]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(

    by="CV Mean R2",

    ascending=False

)

results_df

In [ ]:
from sklearn.metrics import (

    r2_score,
    mean_absolute_error,
    mean_squared_error

)

In [ ]:
from sklearn.metrics import (

    r2_score,
    mean_absolute_error,
    mean_squared_error

)

test_results = []

for model_name, pipeline in models.items():

    # TRAIN MODEL
  

    pipeline.fit(
        X_train,
        y_train
    )



    
    # TRAIN PREDICTIONS
    

    y_train_pred = pipeline.predict(
        X_train
    )



    
    # TEST PREDICTIONS
    

    y_test_pred = pipeline.predict(
        X_test
    )



    
    # TRAIN METRICS
    

    train_r2 = r2_score(
        y_train,
        y_train_pred
    )

    train_rmse = np.sqrt(
        mean_squared_error(
            y_train,
            y_train_pred
        )
    )



    
    # TEST METRICS
    

    test_r2 = r2_score(
        y_test,
        y_test_pred
    )

    test_rmse = np.sqrt(
        mean_squared_error(
            y_test,
            y_test_pred
        )
    )

    test_mae = mean_absolute_error(
        y_test,
        y_test_pred
    )



    
    # STORE RESULTS
    

    test_results.append({

        "Model": model_name,

        "Train_R2": train_r2,

        "Test_R2": test_r2,

        "Train_RMSE": train_rmse,

        "Test_RMSE": test_rmse,

        "Test_MAE": test_mae

    })



    
    # PRINT RESULTS
    

    print("\n")
    print(model_name)
    

    print("Train R2 :", train_r2)
    print("Test R2  :", test_r2)

    print("Train RMSE :", train_rmse)
    print("Test RMSE  :", test_rmse)

    print("Test MAE :", test_mae)

In [ ]:
results_df = pd.DataFrame(
    test_results
)

results_df = results_df.sort_values(

    by="Test_R2",

    ascending=False

)

results_df

In [ ]:
joblib.dump(
    lgbm_pipeline,
    "lgbm_pipeline.pkl"
)

joblib.dump(
    cat_pipeline,
    "cat_pipeline.pkl"
)

joblib.dump(
    svr_pipeline,
    "svr_pipeline.pkl"
)

joblib.dump(
    rf_pipeline,
    "rf_pipeline.pkl"
)

In [ ]:
joblib.dump(
    xgb_pipeline,
    "xgb_pipeline"
)

In [ ]:
import joblib

joblib.dump(

    X_train.columns,

    "final_feature_columns.pkl"

)

print("Feature columns saved successfully!")

In [ ]:


feature_columns = joblib.load(
    "final_feature_columns.pkl"
)

In [ ]:
feature_columns[:10]

In [ ]:
len(feature_columns)

In [ ]:
variance_mask = (

    lgbm_pipeline
    .named_steps["preprocessing"]
    .named_steps["variance_filter"]
    .get_support()

)

In [ ]:
variance_selected_columns = X_train.columns[
    variance_mask
]

In [ ]:
kbest_mask = (

    lgbm_pipeline
    .named_steps["preprocessing"]
    .named_steps["feature_selection"]
    .get_support()

)

In [ ]:
selected_features = variance_selected_columns[
    kbest_mask
]

In [ ]:
len(selected_features)

In [ ]:
joblib.dump(

    selected_features,

    "selected_1000_features.pkl"

)

In [ ]:
selected_features = joblib.load(
    "selected_1000_features.pkl"
)

In [ ]:
selected_features[:10]

In [ ]:
len(selected_features)

In [ ]:
list(selected_features)

In [ ]:
pd.DataFrame(selected_features)