In [4]:
import numpy as np

In [ ]:
import pandas as pd



random_df = pd.DataFrame({

    ("Random Split", "Train R2"): [
        0.914698, 0.953870, 0.911173, 0.971301,
        0.886048, 0.921235, 0.778395, 0.889991
    ],

    ("Random Split", "Test R2"): [
        0.822533, 0.818310, 0.813091, 0.796399,
        0.794461, 0.790574, 0.756002, 0.746003
    ],

    ("Random Split", "Train RMSE"): [
        0.694434, 0.510671, 0.708638, 0.402799,
        0.802626, 0.667295, 1.119287, 0.788616
    ],

    ("Random Split", "Test RMSE"): [
        0.980893, 0.992495, 1.006649, 1.050637,
        1.055625, 1.065560, 1.150155, 1.173485
    ],

    ("Random Split", "Test MAE"): [
        0.650984, 0.647379, 0.673194, 0.684093,
        0.732121, 0.686932, 0.822527, 0.759461
    ],

    ("Random Split", "CV Mean R2"): [
        0.795394, 0.789168, 0.789499, 0.759817,
        0.769578, 0.771929, 0.731828, 0.755897
    ],

    ("Random Split", "CV Std"): [
        0.016655, 0.017198, 0.016584, 0.023074,
        0.017246, 0.011880, 0.020236, 0.016148
    ]

},

index=[
    "HistGradient",
    "LightGBM",
    "CatBoost",
    "XGBoost",
    "ExtraTrees",
    "SVR",
    "RandomForest",
    "MLPRegressor"
])



robust_df = pd.DataFrame({

    ("Robust Pipeline", "Train R2"): [
        0.918739, 0.955897, 0.913833, 0.971336,
        0.887057, 0.654765, 0.775229, 0.824694
    ],

    ("Robust Pipeline", "Test R2"): [
        0.816342, 0.812518, 0.807808, 0.794664,
        0.790676, 0.663730, 0.747672, 0.404318
    ],

    ("Robust Pipeline", "Train RMSE"): [
        0.677788, 0.499326, 0.697945, 0.402552,
        0.799064, 1.397041, 1.127253, 0.995519
    ],

    ("Robust Pipeline", "Test RMSE"): [
        0.997857, 1.008190, 1.020775, 1.055105,
        1.065300, 1.350227, 1.169622, 1.797093
    ],

    ("Robust Pipeline", "Test MAE"): [
        0.656229, 0.655764, 0.684030, 0.683840,
        0.739607, 0.975150, 0.834427, 0.870594
    ],

    ("Robust Pipeline", "CV Mean R2"): [
        0.786833, 0.782446, 0.780671, 0.754152,
        0.761500, 0.582762, 0.726417, -21081.551168
    ],

    ("Robust Pipeline", "CV Std"): [
        0.013552, 0.014008, 0.015784, 0.018396,
        0.015191, 0.087400, 0.016142, 42164.165052
    ]

},

index=[
    "HistGradient",
    "LightGBM",
    "CatBoost",
    "XGBoost",
    "ExtraTrees",
    "SVR",
    "RandomForest",
    "MLPRegressor"
])

#

compact_df = pd.DataFrame({

    ("Compact Pipeline", "Train R2"): [
        0.945170, 0.901558, 0.897585, 0.970986,
        0.870824, 0.843676, 0.764595, 0.849183
    ],

    ("Compact Pipeline", "Test R2"): [
        0.808281, 0.802455, 0.795962, 0.787014,
        0.778089, 0.777621, 0.738621, 0.789205
    ],

    ("Compact Pipeline", "Train RMSE"): [
        0.556751, 0.746006, 0.760909, 0.405001,
        0.854560, 0.940078, 1.153611, 0.923371
    ],

    ("Compact Pipeline", "Test RMSE"): [
        1.019520, 1.034893, 1.051765, 1.074580,
        1.096864, 1.098018, 1.190414, 1.069038
    ],

    ("Compact Pipeline", "Test MAE"): [
        0.679924, 0.695655, 0.706987, 0.712571,
        0.763075, 0.716527, 0.853333, 0.730382
    ],

    ("Compact Pipeline", "CV Mean R2"): [
        0.775907, 0.776791, 0.771882, 0.744909,
        0.750707, 0.756126, 0.714908, 0.754173
    ],

    ("Compact Pipeline", "CV Std"): [
        0.016030, 0.016982, 0.016325, 0.022785,
        0.017468, 0.020129, 0.020272, 0.014055
    ]

},

index=[
    "LightGBM",
    "HistGradient",
    "CatBoost",
    "XGBoost",
    "ExtraTrees",
    "SVR",
    "RandomForest",
    "MLPRegressor"
])



def style_dataframe(df):

    positive_cols = [
        col for col in df.columns
        if "R2" in col[1]
    ]

    negative_cols = [
        col for col in df.columns
        if "RMSE" in col[1]
        or "MAE" in col[1]
        or "Std" in col[1]
    ]

    return (
        df.style

        # Higher is better
        .background_gradient(
            cmap="RdYlGn",
            subset=positive_cols
        )

        # Lower is better
        .background_gradient(
            cmap="RdYlGn_r",
            subset=negative_cols
        )

        .format("{:.4f}")
    )



display(style_dataframe(random_df))
display(style_dataframe(robust_df))
display(style_dataframe(compact_df))

In [18]:
combine_split = pd.concat([random_df, robust_df, compact_df], axis=1)
combine_split

             Random Split                                                      \
                 Train R2   Test R2 Train RMSE Test RMSE  Test MAE CV Mean R2
HistGradient     0.914698  0.822533   0.694434  0.980893  0.650984   0.795394
LightGBM         0.953870  0.818310   0.510671  0.992495  0.647379   0.789168
CatBoost         0.911173  0.813091   0.708638  1.006649  0.673194   0.789499
XGBoost          0.971301  0.796399   0.402799  1.050637  0.684093   0.759817
ExtraTrees       0.886048  0.794461   0.802626  1.055625  0.732121   0.769578
SVR              0.921235  0.790574   0.667295  1.065560  0.686932   0.771929
RandomForest     0.778395  0.756002   1.119287  1.150155  0.822527   0.731828
MLPRegressor     0.889991  0.746003   0.788616  1.173485  0.759461   0.755897

                       Robust Pipeline                       ...            \
                CV Std        Train R2   Test R2 Train RMSE  ...  Test MAE
HistGradient  0.016655        0.918739  0.816342   0.677788  ...  0.656229
LightGBM      0.017198        0.955897  0.812518   0.499326  ...  0.655764
CatBoost      0.016584        0.913833  0.807808   0.697945  ...  0.684030
XGBoost       0.023074        0.971336  0.794664   0.402552  ...  0.683840
ExtraTrees    0.017246        0.887057  0.790676   0.799064  ...  0.739607
SVR           0.011880        0.654765  0.663730   1.397041  ...  0.975150
RandomForest  0.020236        0.775229  0.747672   1.127253  ...  0.834427
MLPRegressor  0.016148        0.824694  0.404318   0.995519  ...  0.870594

                                         Compact Pipeline            \
                CV Mean R2        CV Std         Train R2   Test R2
HistGradient      0.786833      0.013552         0.901558  0.802455
LightGBM          0.782446      0.014008         0.945170  0.808281
CatBoost          0.780671      0.015784         0.897585  0.795962
XGBoost           0.754152      0.018396         0.970986  0.787014
ExtraTrees        0.761500      0.015191         0.870824  0.778089
SVR               0.582762      0.087400         0.843676  0.777621
RandomForest      0.726417      0.016142         0.764595  0.738621
MLPRegressor -21081.551168  42164.165052         0.849183  0.789205


             Train RMSE Test RMSE  Test MAE CV Mean R2    CV Std
HistGradient   0.746006  1.034893  0.695655   0.776791  0.016982
LightGBM       0.556751  1.019520  0.679924   0.775907  0.016030
CatBoost       0.760909  1.051765  0.706987   0.771882  0.016325
XGBoost        0.405001  1.074580  0.712571   0.744909  0.022785
ExtraTrees     0.854560  1.096864  0.763075   0.750707  0.017468
SVR            0.940078  1.098018  0.716527   0.756126  0.020129
RandomForest   1.153611  1.190414  0.853333   0.714908  0.020272
MLPRegressor   0.923371  1.069038  0.730382   0.754173  0.014055

[8 rows x 21 columns]

In [20]:
random_df_v2 = pd.DataFrame({

    ("Random Split", "Models"): [
    "HistGradient",
    "LightGBM",
    "CatBoost",
    "XGBoost",
    "ExtraTrees",
    "SVR",
    "RandomForest",
    "MLPRegressor"
],
    
    ("Random Split", "Train R2"): [
        0.914698, 0.953870, 0.911173, 0.971301,
        0.886048, 0.921235, 0.778395, 0.889991
    ],

    ("Random Split", "Test R2"): [
        0.822533, 0.818310, 0.813091, 0.796399,
        0.794461, 0.790574, 0.756002, 0.746003
    ],

    ("Random Split", "Train RMSE"): [
        0.694434, 0.510671, 0.708638, 0.402799,
        0.802626, 0.667295, 1.119287, 0.788616
    ],

    ("Random Split", "Test RMSE"): [
        0.980893, 0.992495, 1.006649, 1.050637,
        1.055625, 1.065560, 1.150155, 1.173485
    ],

    ("Random Split", "Test MAE"): [
        0.650984, 0.647379, 0.673194, 0.684093,
        0.732121, 0.686932, 0.822527, 0.759461
    ],

    ("Random Split", "CV Mean R2"): [
        0.795394, 0.789168, 0.789499, 0.759817,
        0.769578, 0.771929, 0.731828, 0.755897
    ],

    ("Random Split", "CV Std"): [
        0.016655, 0.017198, 0.016584, 0.023074,
        0.017246, 0.011880, 0.020236, 0.016148
    ]

})

random_df_v2

   Random Split                                                                \
         Models  Train R2   Test R2 Train RMSE Test RMSE  Test MAE CV Mean R2
0  HistGradient  0.914698  0.822533   0.694434  0.980893  0.650984   0.795394
1      LightGBM  0.953870  0.818310   0.510671  0.992495  0.647379   0.789168
2      CatBoost  0.911173  0.813091   0.708638  1.006649  0.673194   0.789499
3       XGBoost  0.971301  0.796399   0.402799  1.050637  0.684093   0.759817
4    ExtraTrees  0.886048  0.794461   0.802626  1.055625  0.732121   0.769578
5           SVR  0.921235  0.790574   0.667295  1.065560  0.686932   0.771929
6  RandomForest  0.778395  0.756002   1.119287  1.150155  0.822527   0.731828
7  MLPRegressor  0.889991  0.746003   0.788616  1.173485  0.759461   0.755897


     CV Std
0  0.016655
1  0.017198
2  0.016584
3  0.023074
4  0.017246
5  0.011880
6  0.020236
7  0.016148

In [9]:
import pandas as pd


# STRATIFIED SPLIT — PIPELINE 1


stratified_random_df = pd.DataFrame({

    ("Stratified Split", "Train R2"): [
        0.914116,
        0.954434,
        0.914919,
        0.971178,
        0.903828,
        0.925527,
        0.886884,
        0.781078
    ],

    ("Stratified Split", "Test R2"): [
        0.812496,
        0.812448,
        0.806421,
        0.790606,
        0.790594,
        0.786581,
        0.781134,
        0.740589
    ],

    ("Stratified Split", "Train RMSE"): [
        0.693287,
        0.504985,
        0.690038,
        0.401624,
        0.733637,
        0.645590,
        0.795644,
        1.106881
    ],

    ("Stratified Split", "Test RMSE"): [
        1.029183,
        1.029314,
        1.045722,
        1.087599,
        1.087631,
        1.098004,
        1.111928,
        1.210546
    ],

    ("Stratified Split", "Test MAE"): [
        0.685376,
        0.668063,
        0.696994,
        0.724102,
        0.747938,
        0.701975,
        0.769035,
        0.868617
    ],

    ("Stratified Split", "CV Mean R2"): [
        0.796604,
        0.789962,
        0.790011,
        0.765027,
        0.752867,
        0.772025,
        0.769577,
        0.735021
    ],

    ("Stratified Split", "CV Std"): [
        0.014489,
        0.017918,
        0.010964,
        0.020965,
        0.029507,
        0.014366,
        0.010055,
        0.011103
    ]

},

index=[
    "HistGradient",
    "LightGBM",
    "CatBoost",
    "XGBoost",
    "MLPRegressor",
    "SVR",
    "ExtraTrees",
    "RandomForest"
])

# STRATIFIED SPLIT — ROBUST PIPELINE

stratified_robust_df = pd.DataFrame({

    ("Robust Pipeline", "Train R2"): [
        0.918999,
        0.914281,
        0.956794,
        0.971280,
        0.888952,
        0.779704,
        0.478728,
        0.703844
    ],

    ("Robust Pipeline", "Test R2"): [
        0.801238,
        0.797758,
        0.797198,
        0.780532,
        0.766556,
        0.731061,
        0.472702,
        -82831.795780
    ],

    ("Robust Pipeline", "Train RMSE"): [
        0.673291,
        0.692618,
        0.491732,
        0.400911,
        0.788337,
        1.110348,
        1.708003,
        1.287410
    ],

    ("Robust Pipeline", "Test RMSE"): [
        1.059628,
        1.068866,
        1.070343,
        1.113456,
        1.148362,
        1.232577,
        1.725898,
        684.050807
    ],

    ("Robust Pipeline", "Test MAE"): [
        0.704804,
        0.717775,
        0.698014,
        0.728804,
        0.789482,
        0.881143,
        1.299786,
        16.244059
    ],

    ("Robust Pipeline", "CV Mean R2"): [
        0.790705,
        0.781471,
        0.786097,
        0.760178,
        0.763732,
        0.731455,
        0.436779,
        0.175208
    ],

    ("Robust Pipeline", "CV Std"): [
        0.013378,
        0.013282,
        0.016918,
        0.015058,
        0.010770,
        0.010809,
        0.032185,
        0.642315
    ]

},

index=[
    "HistGradient",
    "CatBoost",
    "LightGBM",
    "XGBoost",
    "ExtraTrees",
    "RandomForest",
    "SVR",
    "MLPRegressor"
])

# STRATIFIED SPLIT — COMPACT PIPELINE


stratified_compact_df = pd.DataFrame({

    ("Compact Pipeline", "Train R2"): [
        0.946651,
        0.900910,
        0.901540,
        0.842462,
        0.842588,
        0.970777,
        0.872266,
        0.765869
    ],

    ("Compact Pipeline", "Test R2"): [
        0.787450,
        0.783941,
        0.782848,
        0.780275,
        0.772086,
        0.767314,
        0.760282,
        0.722763
    ],

    ("Compact Pipeline", "Train RMSE"): [
        0.546411,
        0.744681,
        0.742311,
        0.938964,
        0.938589,
        0.404408,
        0.845493,
        1.144685
    ],

    ("Compact Pipeline", "Test RMSE"): [
        1.095766,
        1.104774,
        1.107565,
        1.114108,
        1.134679,
        1.146496,
        1.163690,
        1.251447
    ],

    ("Compact Pipeline", "Test MAE"): [
        0.719086,
        0.741077,
        0.746783,
        0.766905,
        0.743577,
        0.762262,
        0.806820,
        0.891080
    ],

    ("Compact Pipeline", "CV Mean R2"): [
        0.775089,
        0.776265,
        0.773762,
        0.744066,
        0.754714,
        0.749828,
        0.751768,
        0.717502
    ],

    ("Compact Pipeline", "CV Std"): [
        0.012955,
        0.014739,
        0.011420,
        0.008070,
        0.009219,
        0.010977,
        0.011604,
        0.010716
    ]

},

index=[
    "LightGBM",
    "HistGradient",
    "CatBoost",
    "MLPRegressor",
    "SVR",
    "XGBoost",
    "ExtraTrees",
    "RandomForest"
])


# STYLING FUNCTION


def style_dataframe(df):

    positive_cols = [
        col for col in df.columns
        if "R2" in col[1]
    ]

    negative_cols = [
        col for col in df.columns
        if "RMSE" in col[1]
        or "MAE" in col[1]
        or "Std" in col[1]
    ]

    return (
        df.style

        # Higher is better
        .background_gradient(
            cmap="RdYlGn",
            subset=positive_cols
        )

        # Lower is better
        .background_gradient(
            cmap="RdYlGn_r",
            subset=negative_cols
        )

        .format("{:.4f}")
    )


# DISPLAY


display(style_dataframe(stratified_random_df))
display(style_dataframe(stratified_robust_df))
display(style_dataframe(stratified_compact_df))

In [12]:
print(random_results.dtypes)

Pipeline       object
Model          object
Test R2       float64
Test RMSE     float64
Test MAE      float64
CV Mean R2    float64
CV Std        float64
dtype: object

In [13]:
from IPython.display import display_html
import pandas as pd

# ==========================================================
# HELPER
# ==========================================================

def create_table(df, pipeline_name):

    temp = df.copy()

    # Flatten MultiIndex columns
    temp.columns = [c[1] for c in temp.columns]

    temp["Model"] = temp.index
    temp["Pipeline"] = pipeline_name

    temp = temp.reset_index(drop=True)

    return temp


# ==========================================================
# RANDOM SPLIT
# ==========================================================

random_results = pd.concat([
    create_table(random_df, "Baseline"),
    create_table(robust_df, "Robust"),
    create_table(compact_df, "Compact")
], ignore_index=True)

random_results = random_results[
    [
        "Pipeline",
        "Model",
        "Test R2",
        "Test RMSE",
        "Test MAE",
        "CV Mean R2",
        "CV Std"
    ]
]

random_results = random_results.sort_values(
    by=["Test R2", "CV Mean R2"],
    ascending=[False, False]
).reset_index(drop=True)

random_results.insert(
    0,
    "Rank",
    range(1, len(random_results) + 1)
)

# ==========================================================
# STRATIFIED SPLIT
# ==========================================================

stratified_results = pd.concat([
    create_table(stratified_random_df, "Baseline"),
    create_table(stratified_robust_df, "Robust"),
    create_table(stratified_compact_df, "Compact")
], ignore_index=True)

stratified_results = stratified_results[
    [
        "Pipeline",
        "Model",
        "Test R2",
        "Test RMSE",
        "Test MAE",
        "CV Mean R2",
        "CV Std"
    ]
]

stratified_results = stratified_results.sort_values(
    by=["Test R2", "CV Mean R2"],
    ascending=[False, False]
).reset_index(drop=True)

stratified_results.insert(
    0,
    "Rank",
    range(1, len(stratified_results) + 1)
)

# ==========================================================
# STYLING
# ==========================================================

random_html = (
    random_results.style
    .background_gradient(
        cmap="RdYlGn",
        subset=["Test R2", "CV Mean R2"]
    )
    .background_gradient(
        cmap="RdYlGn_r",
        subset=["Test RMSE", "Test MAE", "CV Std"]
    )
    .format({
        "Test R2": "{:.4f}",
        "Test RMSE": "{:.4f}",
        "Test MAE": "{:.4f}",
        "CV Mean R2": "{:.4f}",
        "CV Std": "{:.4f}"
    })
    .hide(axis="index")
    .to_html()
)

stratified_html = (
    stratified_results.style
    .background_gradient(
        cmap="RdYlGn",
        subset=["Test R2", "CV Mean R2"]
    )
    .background_gradient(
        cmap="RdYlGn_r",
        subset=["Test RMSE", "Test MAE", "CV Std"]
    )
    .format({
        "Test R2": "{:.4f}",
        "Test RMSE": "{:.4f}",
        "Test MAE": "{:.4f}",
        "CV Mean R2": "{:.4f}",
        "CV Std": "{:.4f}"
    })
    .hide(axis="index")
    .to_html()
)

# ==========================================================
# DISPLAY SIDE BY SIDE
# ==========================================================

html = f"""
<div style="display:flex;gap:40px;align-items:flex-start">

<div style="width:50%">
<h2>🎲 Random Split Models</h2>
{random_html}
</div>

<div style="width:50%">
<h2>📊 Stratified Split Models</h2>
{stratified_html}
</div>

</div>
"""

display_html(html, raw=True)

Rank,Pipeline,Model,Test R2,Test RMSE,Test MAE,CV Mean R2,CV Std
1,Baseline,HistGradient,0.8225,0.9809,0.6510,0.7954,0.0167
2,Baseline,LightGBM,0.8183,0.9925,0.6474,0.7892,0.0172
3,Robust,HistGradient,0.8163,0.9979,0.6562,0.7868,0.0136
4,Baseline,CatBoost,0.8131,1.0066,0.6732,0.7895,0.0166
5,Robust,LightGBM,0.8125,1.0082,0.6558,0.7824,0.0140
6,Compact,LightGBM,0.8083,1.0195,0.6799,0.7759,0.0160
7,Robust,CatBoost,0.8078,1.0208,0.6840,0.7807,0.0158
8,Compact,HistGradient,0.8025,1.0349,0.6957,0.7768,0.0170
9,Baseline,XGBoost,0.7964,1.0506,0.6841,0.7598,0.0231
10,Compact,CatBoost,0.7960,1.0518,0.7070,0.7719,0.0163
11,Robust,XGBoost,0.7947,1.0551,0.6838,0.7542,0.0184
12,Baseline,ExtraTrees,0.7945,1.0556,0.7321,0.7696,0.0172
13,Robust,ExtraTrees,0.7907,1.0653,0.7396,0.7615,0.0152
14,Baseline,SVR,0.7906,1.0656,0.6869,0.7719,0.0119
15,Compact,MLPRegressor,0.7892,1.0690,0.7304,0.7542,0.0141
16,Compact,XGBoost,0.7870,1.0746,0.7126,0.7449,0.0228
17,Compact,ExtraTrees,0.7781,1.0969,0.7631,0.7507,0.0175
18,Compact,SVR,0.7776,1.0980,0.7165,0.7561,0.0201
19,Baseline,RandomForest,0.7560,1.1502,0.8225,0.7318,0.0202
20,Robust,RandomForest,0.7477,1.1696,0.8344,0.7264,0.0161
21,Baseline,MLPRegressor,0.7460,1.1735,0.7595,0.7559,0.0161
22,Compact,RandomForest,0.7386,1.1904,0.8533,0.7149,0.0203
23,Robust,SVR,0.6637,1.3502,0.9751,0.5828,0.0874
24,Robust,MLPRegressor,0.4043,1.7971,0.8706,-21081.5512,42164.1651
Rank,Pipeline,Model,Test R2,Test RMSE,Test MAE,CV Mean R2,CV Std
1,Baseline,HistGradient,0.8125,1.0292,0.6854,0.7966,0.0145
2,Baseline,LightGBM,0.8124,1.0293,0.6681,0.7900,0.0179
3,Baseline,CatBoost,0.8064,1.0457,0.6970,0.7900,0.0110
4,Robust,HistGradient,0.8012,1.0596,0.7048,0.7907,0.0134
5,Robust,CatBoost,0.7978,1.0689,0.7178,0.7815,0.0133
6,Robust,LightGBM,0.7972,1.0703,0.6980,0.7861,0.0169
7,Baseline,XGBoost,0.7906,1.0876,0.7241,0.7650,0.0210
8,Baseline,MLPRegressor,0.7906,1.0876,0.7479,0.7529,0.0295
9,Compact,LightGBM,0.7874,1.0958,0.7191,0.7751,0.0130
10,Baseline,SVR,0.7866,1.0980,0.7020,0.7720,0.0144
11,Compact,HistGradient,0.7839,1.1048,0.7411,0.7763,0.0147
12,Compact,CatBoost,0.7828,1.1076,0.7468,0.7738,0.0114
13,Baseline,ExtraTrees,0.7811,1.1119,0.7690,0.7696,0.0101
14,Robust,XGBoost,0.7805,1.1135,0.7288,0.7602,0.0151
15,Compact,MLPRegressor,0.7803,1.1141,0.7669,0.7441,0.0081
16,Compact,SVR,0.7721,1.1347,0.7436,0.7547,0.0092
17,Compact,XGBoost,0.7673,1.1465,0.7623,0.7498,0.0110
18,Robust,ExtraTrees,0.7666,1.1484,0.7895,0.7637,0.0108
19,Compact,ExtraTrees,0.7603,1.1637,0.8068,0.7518,0.0116
20,Baseline,RandomForest,0.7406,1.2105,0.8686,0.7350,0.0111
21,Robust,RandomForest,0.7311,1.2326,0.8811,0.7315,0.0108
22,Compact,RandomForest,0.7228,1.2514,0.8911,0.7175,0.0107
23,Robust,SVR,0.4727,1.7259,1.2998,0.4368,0.0322
24,Robust,MLPRegressor,-82831.7958,684.0508,16.2441,0.1752,0.6423

In [15]:
from IPython.display import display_html
import pandas as pd

# ==================================================
# HELPER
# ==================================================

def build_table(df, pipeline):

    temp = df.copy()

    temp.columns = [c[1] for c in temp.columns]

    temp["Model"] = temp.index
    temp["Pipeline"] = pipeline

    return temp.reset_index(drop=True)


# ==================================================
# RANDOM
# ==================================================

random_results = pd.concat([
    build_table(random_df, "Baseline"),
    build_table(robust_df, "Robust"),
    build_table(compact_df, "Compact")
], ignore_index=True)

random_results = random_results[
    [
        "Pipeline",
        "Model",
        "Test R2",
        "Test RMSE",
        "Test MAE",
        "CV Mean R2",
        "CV Std"
    ]
]

random_results = random_results.sort_values(
    by=[
        "Test R2",
        "Test RMSE",
        "Test MAE",
        "CV Mean R2"
    ],
    ascending=[
        False,
        True,
        True,
        False
    ]
).reset_index(drop=True)

random_results.insert(
    0,
    "Rank",
    range(1, len(random_results)+1)
)

# ==================================================
# STRATIFIED
# ==================================================

stratified_results = pd.concat([
    build_table(stratified_random_df, "Baseline"),
    build_table(stratified_robust_df, "Robust"),
    build_table(stratified_compact_df, "Compact")
], ignore_index=True)

stratified_results = stratified_results[
    [
        "Pipeline",
        "Model",
        "Test R2",
        "Test RMSE",
        "Test MAE",
        "CV Mean R2",
        "CV Std"
    ]
]

stratified_results = stratified_results.sort_values(
    by=[
        "Test R2",
        "Test RMSE",
        "Test MAE",
        "CV Mean R2"
    ],
    ascending=[
        False,
        True,
        True,
        False
    ]
).reset_index(drop=True)

stratified_results.insert(
    0,
    "Rank",
    range(1, len(stratified_results)+1)
)

# ==================================================
# STYLING
# ==================================================

random_html = (
    random_results.style
    .background_gradient(
        cmap="RdYlGn",
        subset=["Test R2", "CV Mean R2"]
    )
    .background_gradient(
        cmap="RdYlGn_r",
        subset=["Test RMSE", "Test MAE", "CV Std"]
    )
    .format({
        "Test R2":"{:.4f}",
        "Test RMSE":"{:.4f}",
        "Test MAE":"{:.4f}",
        "CV Mean R2":"{:.4f}",
        "CV Std":"{:.4f}"
    })
    .to_html()
)

stratified_html = (
    stratified_results.style
    .background_gradient(
        cmap="RdYlGn",
        subset=["Test R2", "CV Mean R2"]
    )
    .background_gradient(
        cmap="RdYlGn_r",
        subset=["Test RMSE", "Test MAE", "CV Std"]
    )
    .format({
        "Test R2":"{:.4f}",
        "Test RMSE":"{:.4f}",
        "Test MAE":"{:.4f}",
        "CV Mean R2":"{:.4f}",
        "CV Std":"{:.4f}"
    })
    .to_html()
)

# ==================================================
# SIDE BY SIDE DISPLAY
# ==================================================

display_html(
f"""
<div style="display:flex; align-items:flex-start; gap:25px;">

<div style="width:50%;">
<h3>🎲 RANDOM SPLIT LEADERBOARD</h3>
{random_html}
</div>

<div style="width:50%;">
<h3>📊 STRATIFIED SPLIT LEADERBOARD</h3>
{stratified_html}
</div>

</div>
""",
raw=True
)

,Rank,Pipeline,Model,Test R2,Test RMSE,Test MAE,CV Mean R2,CV Std
0,1,Baseline,HistGradient,0.8225,0.9809,0.6510,0.7954,0.0167
1,2,Baseline,LightGBM,0.8183,0.9925,0.6474,0.7892,0.0172
2,3,Robust,HistGradient,0.8163,0.9979,0.6562,0.7868,0.0136
3,4,Baseline,CatBoost,0.8131,1.0066,0.6732,0.7895,0.0166
4,5,Robust,LightGBM,0.8125,1.0082,0.6558,0.7824,0.0140
5,6,Compact,LightGBM,0.8083,1.0195,0.6799,0.7759,0.0160
6,7,Robust,CatBoost,0.8078,1.0208,0.6840,0.7807,0.0158
7,8,Compact,HistGradient,0.8025,1.0349,0.6957,0.7768,0.0170
8,9,Baseline,XGBoost,0.7964,1.0506,0.6841,0.7598,0.0231
9,10,Compact,CatBoost,0.7960,1.0518,0.7070,0.7719,0.0163
10,11,Robust,XGBoost,0.7947,1.0551,0.6838,0.7542,0.0184
11,12,Baseline,ExtraTrees,0.7945,1.0556,0.7321,0.7696,0.0172
12,13,Robust,ExtraTrees,0.7907,1.0653,0.7396,0.7615,0.0152
13,14,Baseline,SVR,0.7906,1.0656,0.6869,0.7719,0.0119
14,15,Compact,MLPRegressor,0.7892,1.0690,0.7304,0.7542,0.0141
15,16,Compact,XGBoost,0.7870,1.0746,0.7126,0.7449,0.0228
16,17,Compact,ExtraTrees,0.7781,1.0969,0.7631,0.7507,0.0175
17,18,Compact,SVR,0.7776,1.0980,0.7165,0.7561,0.0201
18,19,Baseline,RandomForest,0.7560,1.1502,0.8225,0.7318,0.0202
19,20,Robust,RandomForest,0.7477,1.1696,0.8344,0.7264,0.0161
20,21,Baseline,MLPRegressor,0.7460,1.1735,0.7595,0.7559,0.0161
21,22,Compact,RandomForest,0.7386,1.1904,0.8533,0.7149,0.0203
22,23,Robust,SVR,0.6637,1.3502,0.9751,0.5828,0.0874
23,24,Robust,MLPRegressor,0.4043,1.7971,0.8706,-21081.5512,42164.1651
,Rank,Pipeline,Model,Test R2,Test RMSE,Test MAE,CV Mean R2,CV Std
0,1,Baseline,HistGradient,0.8125,1.0292,0.6854,0.7966,0.0145
1,2,Baseline,LightGBM,0.8124,1.0293,0.6681,0.7900,0.0179
2,3,Baseline,CatBoost,0.8064,1.0457,0.6970,0.7900,0.0110
3,4,Robust,HistGradient,0.8012,1.0596,0.7048,0.7907,0.0134
4,5,Robust,CatBoost,0.7978,1.0689,0.7178,0.7815,0.0133
5,6,Robust,LightGBM,0.7972,1.0703,0.6980,0.7861,0.0169
6,7,Baseline,XGBoost,0.7906,1.0876,0.7241,0.7650,0.0210
7,8,Baseline,MLPRegressor,0.7906,1.0876,0.7479,0.7529,0.0295
8,9,Compact,LightGBM,0.7874,1.0958,0.7191,0.7751,0.0130
9,10,Baseline,SVR,0.7866,1.0980,0.7020,0.7720,0.0144
10,11,Compact,HistGradient,0.7839,1.1048,0.7411,0.7763,0.0147
11,12,Compact,CatBoost,0.7828,1.1076,0.7468,0.7738,0.0114
12,13,Baseline,ExtraTrees,0.7811,1.1119,0.7690,0.7696,0.0101
13,14,Robust,XGBoost,0.7805,1.1135,0.7288,0.7602,0.0151
14,15,Compact,MLPRegressor,0.7803,1.1141,0.7669,0.7441,0.0081
15,16,Compact,SVR,0.7721,1.1347,0.7436,0.7547,0.0092
16,17,Compact,XGBoost,0.7673,1.1465,0.7623,0.7498,0.0110
17,18,Robust,ExtraTrees,0.7666,1.1484,0.7895,0.7637,0.0108
18,19,Compact,ExtraTrees,0.7603,1.1637,0.8068,0.7518,0.0116
19,20,Baseline,RandomForest,0.7406,1.2105,0.8686,0.7350,0.0111
20,21,Robust,RandomForest,0.7311,1.2326,0.8811,0.7315,0.0108
21,22,Compact,RandomForest,0.7228,1.2514,0.8911,0.7175,0.0107
22,23,Robust,SVR,0.4727,1.7259,1.2998,0.4368,0.0322
23,24,Robust,MLPRegressor,-82831.7958,684.0508,16.2441,0.1752,0.6423